### ISSUE TITLE
User profile page pending

### ISSUE THREAD

**Issue by ekansh2112** [Khush24Shah/IT632_2_ThriftKart#8]

**Comment by alwaysstaycalm24** [comment]
[UserProfile.zip](https://github.com/Khush24Shah/IT632_2_ThriftKart/files/8663703/UserProfile.zip)

**Comment by alwaysstaycalm24** [comment]
[UserProfile.zip](https://github.com/Khush24Shah/IT632_2_ThriftKart/files/8663707/UserProfile.zip)
